# Generated by Django 5.0.2 on 2024-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("plot", models.TextField(blank=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="catalog.actor"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="catalog.director"
                    ),
                ),
            ],
            options={
                "ordering": ("year",),
            },
        ),
    ]
